### ISSUE TITLE
How to query a historical snapshot?

### ISSUE THREAD

**Issue by ealashwali** [google/safebrowsing#100]
Hi, sorry if this question outside the issues scope but I will appreciate your help as I could not find answers elesewhere. I used this project to run the Google safe browsing DB and make queries locally using Ubunutu. My terminal shows me lines of updates such as: 
```

 safebrowsing: 2019/06/28 12:01:09 database.go:111: no database file specified
safebrowsing: 2019/06/28 12:01:10 database.go:243: Server requested next update in 30m24.304s
safebrowsing: 2019/06/28 12:01:11 database.go:389: database is now healthy
safebrowsing: 2019/06/28 12:01:11 safebrowser.go:557: Next update in 30m24.304s
Starting server at localhost:8080
```
I assume that the DB automatically receive updates. Plz correct me if I'm wrong and if I need to do anything to keep it up to date.

The second issue, if I use this project, can I get a snapshot of older specific date? e.g. the DB two months ago? Plz let me know if there is anyway to query the DB on old date.

**Comment by colonelxc** [comment]
Yes, it will automatically get updates, approximately every 30 minutes.

For historical snapshots, you could modify the code to save each update to a different file, then analyze them later. An important note is that the 'db' only contains hash prefixes (not full url hashes), so you might see a match on the prefix, but verification involves sending that prefix to the server, to get the full hash (and finally matching your local full hash with the one retrieved from the server).

The responses from the server are only for things that are 'current' in the blacklist (If you query an old hash prefix that is no longer blacklisted, you will not get the full hash back). This drastically limits the use of keeping old DBs around, as you can't be sure if there was an actual match, or just a hash-prefix collision.

The server also does not provide for querying for older dbs. It does keep some amount of older state in order to efficiently update clients by supplying just the minimum additions/deletions to get the client to the latest DB version, but that is all.
