### ISSUE TITLE
curl example in sbserver comments

### ISSUE THREAD

**Issue by muahtorski** [google/safebrowsing#15]
Minor issue with "Example usage" curl command in comments of /cmd/sbserver/main.go. The url being evaluated should be appended with [PLATFORM]/[THREAT TYPE]/[THEAT ENTRY TYPE].  Working example:

```
$ curl \
  -H "Content-Type: application/json" \
  -X POST -d '{
      "threatInfo": {
          "threatTypes":      ["UNWANTED_SOFTWARE", "MALWARE"],
          "platformTypes":    ["ANY_PLATFORM"],
          "threatEntryTypes": ["URL"],
          "threatEntries": [
              {"url": "http://testsafebrowsing.appspot.com/apiv4/ANY_PLATFORM/MALWARE/URL/"}
          ]
      }
  }' \
  localhost:8080/v4/threatMatches:find
```

**Comment by dsnet** [comment]
The example was simply trying to show how to use sbserver, but not necessarily that the URLs used will report the same. The use of URLs like "bad1url.org" does have the advantage that it makes the examples more readable.

I do agree that it would be nice if the examples actually worked (when directly executed), though.

@shahbag, are you aware of shorter "bad" URLs to use as examples? Otherwise, we can switch them to be the http://testsafebrowsing.appspot.com/apiv4/... ones.

**Comment by shahbag** [comment]
We can only use the http://testsafebrowsing.appspot.com/apiv4/ ones as working examples
