### ISSUE TITLE
URLs without trailing slash are not detected as unsafe

### ISSUE THREAD

**Issue by lcf** [google/safebrowsing#36]
This was detected as we were testing a Java implementation of the Update API (v4). The Go client has the same issue

```
~$ echo "http://malware.testing.google.test/testing/malware" | sblookup -apikey=$GOOGLEAPIKEY
safebrowsing: 2016/09/29 23:32:01 database.go:100: no database file specified
safebrowsing: 2016/09/29 23:32:06 database.go:291: database is now healthy
Safe URL: http://malware.testing.google.test/testing/malware
~$ echo "http://malware.testing.google.test/testing/malware/" | sblookup -apikey=$GOOGLEAPIKEY
safebrowsing: 2016/09/29 23:32:15 database.go:100: no database file specified
safebrowsing: 2016/09/29 23:32:20 database.go:291: database is now healthy
Unsafe URL: [{malware.testing.google.test/testing/malware/ {MALWARE ANY_PLATFORM URL}}]
```

Yet "Safe Browsing Site Status" status page shows both https://www.google.com/transparencyreport/safebrowsing/diagnostic/#url=http://malware.testing.google.test/testing/malware 

as Dangerous.

**Comment by noelutz** [comment]
Thanks for reporting. Turns out the API is WAI. The diagnostic page shouldn't flag this pattern as dangerous. I reported this bug to the relevant colleague.

Details: the API considers a.com/foo and a.com/foo/ as two different (non-covering) patterns. I.e., if one gets listed the other one is still considered safe. If both are unsafe then we would either flag a.com/ as unsafe or flag both patterns as unsafe.

**Comment by noelutz** [comment]
Further details that may help: if we flag a.com/foo/ then any resource under that directory is considered unsafe. E.g., a.com/foo/bar would be considered unsafe. However, if we flag a.com/foo only that path is unsafe (including any URL parameters, e.g., a.com/foo?a=b would be unsafe).
