### ISSUE TITLE
How to compute prefix hashes?

### ISSUE THREAD

**Issue by papaiatis** [google/safebrowsing#41]
Hi,

I'm interested in how the prefix hashes are computed.
The API docs says "the client needs to compute the hash prefix for each full-length SHA256 hash". 
I've been reading this Go code for a while now but can't figure out how you compute the hash prefixes.

Any help would be appreciated!

Thanks!

**Comment by mikecb** [comment]
The API docs have a pretty good description of what one has to do to use the Update API, including canonicalization and hashing: https://developers.google.com/safe-browsing/v4/urls-hashing

**Comment by papaiatis** [comment]
I've been reading that exact page for hours, but there is one particular thing I can't understand, and that is in which cases a prefix hash can be longer than 4 bytes?
So let's say I have an URL which I canonicalize and compute all the full hashes. 
Now I have many full hashes for which I need to compute prefix hashes. In which cases a prefix hash should be 4 bytes, 5 bytes, ..., 32 bytes?

**Comment by alexwoz** [comment]
@papaiatis Since Safe Browsing may distribute hash prefixes of length [4, 32] bytes, the data structure used to store these hashes should take that into account. This repo's implementation maintains two hash maps, one that maps a 4-byte prefix to the maximum size of a stored hash with that prefix in that database, and another one that maps prefixes which are > 4-bytes in length to an empty struct. Here's how a hash prefix is looked up: https://github.com/google/safebrowsing/blob/master/hash.go#L140

Hopefully that helps!

**Comment by singhikjot** [comment]
> I've been reading that exact page for hours, but there is one particular thing I can't understand, and that is in which cases a prefix hash can be longer than 4 bytes?
> So let's say I have an URL which I canonicalize and compute all the full hashes.
> Now I have many full hashes for which I need to compute prefix hashes. In which cases a prefix hash should be 4 bytes, 5 bytes, ..., 32 bytes?

Hi,
Can you share your code how you have converted URI to hash and prefix Hash. I am having some problem in converting

**Comment by colonelxc** [comment]
https://github.com/google/safebrowsing/blob/master/hash.go is where we are doing the hashing, which is just performing a sha256. An important note is that the API uses the binary output of a sha256. Some languages (such as php) default to outputing a textual representation of the hex bytes instead.

More useful is probably https://github.com/google/safebrowsing/blob/master/urls.go, which is what takes a single url, and turns it into a bunch of different 'expressions', which are each individually hashed (and taken the prefix of, and then checked versus the database, following the rules of https://developers.google.com/safe-browsing/v4/urls-hashing). 

So I guess I would first check to make sure you are canoncilizing the urls as expected, then check that you can generate the expected prefix/suffix expressions, then deal with getting the hash prefixes.  There are examples of all three of those pieces in the developer doc linked in the above paragraph.

**Comment by NetMage** [comment]
All that page says is literally "hash prefix consists of the most significant 4-32 bytes of a SHA256 hash" which says nothing about how you decide how many bytes constitute "most significant" and examples are no help and also a terrible way to provide information.
Update:  I think I understand - since you are comparing the local database of hash prefixes to your computed full hash, you must compare each one based on the size of the prefix in the local database. That seems a poor design - instead of being  able to grab a prefix and search the database, you have to partition the prefixes by length and then compare then truncate the full hash to each partitions prefix size and see if there is a match.

**Comment by colonelxc** [comment]
Sorry for the confusion.

The output of a sha256 is essentially a 256 bit number. So the 'most significant' bits of that number are the ones that make the largest difference in the value of that number. Which is just a confusing way to say, "the first few bytes" (I think you understand this now from your update. If you have more questions about it, please open a new bug).

The design does make the clients complicated, but it isn't without reason. It would be much simpler if we just said "Always use a 4 byte prefix". But in some cases, a flagged phishing/malware site might have a 4 byte hash collision with a very popular site (say, google.com), and cause a lot of unnecessary requests for the full hash lookup.

Essentially, the API is designed around both privacy and bandwidth concerns, so we want to ship the least amount of bytes necessary, but we also don't want clients to have to make too many extra checks because of the short prefixes. Also, it's a pretty good DDoS when it happens (SB has over 3 billion active clients).

**Comment by NetMage** [comment]
Now that I have your attention... :) 
Given the recent tempest about iPhone usage of the Safe Browsing API, are any statistics available on bucket size ranges, or total number of bad hashes, or prefix size ranges?

**Comment by colonelxc** [comment]
As I mentioned in the last comment, please open new issues for different questions. Everyone in the thread will be notified when you post on this old issue.

I don't have specific statistics, but 4-byte hashes are almost always used. It's the default size, and we only need to increase it to avoid problematic hash collisions. When we extend them, we only need to extend them enough bytes to break the collision (typically, only one byte). It'd be easy for a client to perform their own independent statistics as well, because of course it's public for anyone to sign up for the API and start downloading lists.
