### ISSUE TITLE
Support go1.6

### ISSUE THREAD

**Issue by SvenAbels** [google/safebrowsing#64]
After receiving the #63 (compression type) error, I tried to do a fresh

>  go get github.com/google/safebrowsing/cmd/sblookup

whcih results in an 

> package context: unrecognized import path "context" (import path does not begin with hostname)

**Comment by dsnet** [comment]
What version of Go are you running? `context` was introduced into the Go standard library in Go1.7.

**Comment by SvenAbels** [comment]
v1.6 as this is the standard version in the latest Ubuntu 16.04 LTS. Is there a way to still use Go 1.6?

**Comment by dsnet** [comment]
Many Go projects only really support the latest two versions of Go (i.e., 1.7 and 1.8).
However, this repo could be made to work with Go1.6 by importing `"golang.org/x/net/context"` instead of just `"context"`

`"golang.org/x/net/context"` is mostly a drop-in replacement, unless someone created an interface where one of the methods is `WaitUntilReady`. This does not build since the `context.Context` type would not be exactly identical. Type aliases in Go1.9 fixes this problem, but that's kinda unhelpful in this situation...

**Comment by SvenAbels** [comment]
OK, I understand. I will update to go 1.8 in that case.

The nice thing about supporting 1.6 is that is allows a very easy creation of a dockerized verision because you can simply base a docker image on the standard ubuntu image
