### ISSUE TITLE
API outage? inconsistent database: unexpected server 503

### ISSUE THREAD

**Issue by cpu** [google/safebrowsing#68]
Hi folks :wave:,

Between 13:07:00 pm UTC and 13:34:00 UTC today we began seeing 503 errors returned by the Safebrowsing v4 API, causing traces from the database Status and a cached err:

> safebrowser.go:400: inconsistent database: safebrowsing: unexpected server response code: 503

A couple questions:

1) Is there a status page specifically for the Google Safe Browsing API? I wasn't able to find one with some quick searching. Maybe there's a way to find this status in the Google developers panel somewhere? Pointers appreciated!

2) Can you confirm that this was a temporary API event? Should we expect that the root cause has since been resolved?

Thanks!

**Comment by alexwoz** [comment]
Hi Daniel,

Thanks for reaching out. A subset of clients were indeed affected by a brief outage this morning (13:00-13:30 UTC). This has since been resolved. Do let us know whether you continue to experience issues.

We currently do not offer a service status page, but it's a great suggestion. We'll keep it in mind for future work.

Thanks,
Alex

**Comment by cpu** [comment]
Hi @alexwoz,

Thanks for the quick response - I really appreciate it!

> We currently do not offer a service status page, but it's a great suggestion. We'll keep it in mind for future work.

That would be great. Thank you. I'll close this issue since I suspect it's not the best place for a status page feature request but please count me as a big +1 for the idea :-)
