### ISSUE TITLE
Use context for timeouts

### ISSUE THREAD

**Issue by jsha** [google/safebrowsing#73]
In #59, a config option was added to set a default timeout for the HTTP client. However, there may be a problem: `ListUpdate` and `HashLookup` get the same timeout, but `ListUpdate` probably takes a lot longer in most cases and is not in the blocking path.

Instead, it would be nice to have a variant of LookupURLs that took a context, and would pass that through to `HashLookup`, and from there to the HTTP client so that the caller could set a timeout with more granularity.

**Comment by colonelxc** [comment]
I think passing a context to LookupURLs (or something like LookupURLsWithContext) is a great idea.

So right now, a timeout is set on the http client. That doesn't stop us from adding a context to the request, but we could consider moving all timeout related operations to contexts instead of the http client. I'm not sure which is cleaner.

**Comment by jsha** [comment]
The simplest backwards-compatible way would be to keep the default timeout config option, and combine it with any provided context. So for instance, `LookupURLs` would call `LookupURLsContext(context.Background, ...)`, and `LookupURLsContext(ctx, ...` would call `ctx = context.WithTimeout(ctx, defaultTimeout)`. That way if the passed context has a shorter timeout, it would be observed, but if it has a longer timeout, it would be shortened to match the default timeout.
