### ISSUE TITLE
Guide for developing & running locally

### ISSUE THREAD

**Issue by summera** [google/safebrowsing#79]
New to go and would like to get this running locally but having some issues. Once I downloaded all dependencies and tried `go run main.go` in the `cmd/sbserver` directory I'm getting the following error:

```
main.go:202:2: use of internal package not allowed
```

Some guidance for how to get this running would be greatly appreciated.

**Comment by dsnet** [comment]
Using `go run` doesn't work well where there are dependencies since they can't be resolved easily.

Trying doing:
```
$ go install github.com/google/safebrowsing/cmd/sbserver
$ export `go env | grep GOPATH | sed 's|"||g'`
$ $GOPATH/bin/sbserver
```

**Comment by summera** [comment]
@dsnet Thanks for the response. I should have been more specific. I've got that working. However, I'd like to clone the repo locally, make some changes, and then run the server. So I'm trying to setup the development environment rather than just running the server as is in this repo.

**Comment by dsnet** [comment]
Ah... cloning a repo is unfortunately not something easily works out of the box in Go. That will be fixed with [proper versioning support in the Go tool](https://blog.golang.org/versioning-proposal).

You have two options:
1. Replace all instances of `"github.com/google/safebrowsing"` with `"github.com/summera/safebrowsing"`.
2. Replace `$GOPATH/src/github.com/google/safebrowsing` with a symlink to `$GOPATH/src/github.com/summera/safebrowsing`.

I usually do option 2.

**Comment by dsnet** [comment]
Option 3, you can use `vgo`, which is the prototype for the upcoming versioned Go tool.

```
$ go get -u golang.org/x/vgo
$ echo 'module "github.com/google/safebrowsing"' > $GOPATH/src/github.com/summera/safebrowsing/go.mod
$ cd $GOPATH/src/github.com/summera/safebrowsing/cmd/sbserver
$ vgo build
```

The `go.mod` file provides information about the root import path for this repository.
The `vgo` tool is a wrapper around the `go` tool and knows how to handle `go.mod` files.

**Comment by summera** [comment]
Thanks @dsnet 👍
